---
title: "ensino"
listing:
  - id: em-andamento
    contents: ensino
    type: grid
    sort: "title asc"
    date-format: DD/MM/YYYY
    categories: false
    fields: [image, description, title]
    image-height: 190px
title-block-banner: false
toc-title: "nesta página"
page-layout: full
toc: true
---

você encontra, nesta seção, informações sobre as disciplinas dos meus cursos que estão em andamento e também uma lista com todas as disciplinas que já lecionei na universidade federal de uberlândia.

## cursos em andamento

a seguir, as disciplas que estou lecionando no primeiro semestre letivo de 2024. para acessar as informações de uma disciplina específica, basta clicar sobre sua ficha.

:::{#em-andamento}
:::

## cursos encerrados

- famat31203: probabilidade 1
- ges044: métodos matemáticos (introdução ao aprendizado de máquina)
- ges033: análise de séries temporais
- famat31033: estatística
- gbc041: estatística
- ges017: estatística computacional
- ges022: inferência estatística 2
- ges046: tópicos especiais em matemática aplicada (introdução ao aprendizado estatístico)
- ges012: estatística geral
- famat31041: estatística computacional
- ges035: profissão e mercado de trabalho
- ges008: introdução à estatística 2
- gcc014: estatística
- gci018: estatística
- ges018: inferência estatística 1
- get014: estatística
- ges015: probabilidade 2
- ges031: modelos lineares generalizados
