---
title: "ensino"
listing:
  - id: em-andamento
    contents: ./
    type: grid
    sort: "date"
    date-format: DD/MM/YYYY
    categories: false
    fields: [image, description, title]
    image-height: 190px
    max-description-length: 245
title-block-banner: true
toc-title: "nesta página"
page-layout: full
toc: true
description: |
  nesta página estão listadas as disciplinas que estou lecionando atualmente e os cursos que já lecionei. as informações sobre as disciplinas em andamento estão organizadas em fichas, com links para o conteúdo completo.
---


## cursos em andamento

neste segundo semestre de 2024 estou lecionando três disciplinas: introdução à ciência de dados, probabilidade 1 e inferência estatística 1. as informações de cada uma dessas disciplinas (como bibliografia, ementa, horário de atendimento e datas das provas), estão nas fichas abaixo.

:::{#em-andamento}
:::

## cursos encerrados

- ges045: introdução à história da estatística e da probabilidade
- famat31308: introdução à ciência de dados
- pcda08: processamento automático de textos (especialização em ciência de dados)
- famat31203: probabilidade 1
- ges044: métodos matemáticos (introdução ao aprendizado de máquina)
- ges033: análise de séries temporais
- famat31033: estatística
- gbc041: estatística
- ges017: estatística computacional
- ges022: inferência estatística 2
- ges046: tópicos especiais em matemática aplicada (introdução ao aprendizado estatístico)
- ges012: estatística geral
- famat31041: estatística computacional
- ges035: profissão e mercado de trabalho
- ges008: introdução à estatística 2
- gcc014: estatística
- gci018: estatística
- ges018: inferência estatística 1
- get014: estatística
- ges015: probabilidade 2
- ges031: modelos lineares generalizados
